version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-eb-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gidiuiidrxqu"
s3_prefix = "sam-eb-api"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "BlueDragonURL=\"https://webhook.site/8bdc19db-3ff8-4dbb-ba75-7c6ce17f6b5c\""
image_repositories = []
resolve_s3 = true
